force-app/main/default/objects/Fabulous_Confetti_Message__c/Fabulous_Confetti_Message__c.object-meta.xml
<CustomObject>
    <description>This Object can be used to send confetti messages to certain Users as part of the Fabulous Confetti package.
For the User to receive Confetti the Component &quot;Fabulous Confetti Messages&quot; has to be added to the utility bar.</description>
    <label>Fabulous Confetti Message</label>
    <nameField>
        <displayFormat>FC-{0000000000}</displayFormat>
        <label>Fabulous Confetti Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fabulous Confetti Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fabulous_Confetti_Message__c/fields/Confetti_Type__c.field-meta.xml
<CustomField>
    <fullName>Confetti_Type__c</fullName>
    <inlineHelpText>What type of confetti should be sent. Check the documentation for available confetti types.</inlineHelpText>
    <label>Confetti Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fabulous_Confetti_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <inlineHelpText>What text should be sent to your colleague?</inlineHelpText>
    <label>Message Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fabulous_Confetti_Message__c/fields/Target_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_User_Id__c</fullName>
    <inlineHelpText>To whom should the Confetti be sent?</inlineHelpText>
    <label>Target User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FabulousMessagesController.cls
//Without Sharing to ensure every user can get their own messages but not see other peoples messages
public with sharing class FabulousMessagesController {

    @AuraEnabled(cacheable=false)
    public static List<Fabulous_Confetti_Message__c> getnewMessagesForUser(String userId) {

        //Querry Fabulous Confetti Messages
        List<Fabulous_Confetti_Message__c> myFabulousMessages = new List<Fabulous_Confetti_Message__c>();
        try{
            myFabulousMessages = [SELECT Id, Confetti_Type__c, Target_User_Id__c, Message_Text__c FROM Fabulous_Confetti_Message__c WHERE Target_User_Id__c =: userId WITH SECURITY_ENFORCED];
        }catch(Exception e){
            return myFabulousMessages;
        }
        if(myFabulousMessages.size()>0){
            List<Fabulous_Confetti_Message__c> messagesToDelete = myFabulousMessages.clone();
            delete(messagesToDelete);
        }
        return myFabulousMessages;

    }
}